import os
import sqlite3
from pathlib import Path

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
DB_PATH = Path(os.getenv("DB_PATH", Path(__file__).with_name("masterbook.db")))
STATUSES = {"new", "progress", "done", "cancelled"}
PAYMENTS = {"unpaid", "partial", "paid"}


def using_postgres():
    return bool(DATABASE_URL)


def get_connection():
    if using_postgres():
        import psycopg
        from psycopg.rows import dict_row
        return psycopg.connect(DATABASE_URL, row_factory=dict_row)

    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA foreign_keys=ON")
    c.execute("PRAGMA journal_mode=WAL")
    return c


def init_db():
    with get_connection() as c:
        if using_postgres():
            c.execute("""
            CREATE TABLE IF NOT EXISTS clients(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                name TEXT NOT NULL,
                phone TEXT DEFAULT '',
                address TEXT DEFAULT '',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS jobs(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
                service TEXT NOT NULL,
                price DOUBLE PRECISION NOT NULL DEFAULT 0,
                expenses DOUBLE PRECISION NOT NULL DEFAULT 0,
                address TEXT DEFAULT '',
                job_date DATE DEFAULT CURRENT_DATE,
                comment TEXT DEFAULT '',
                status TEXT NOT NULL DEFAULT 'done',
                payment_status TEXT NOT NULL DEFAULT 'paid',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS expenses(
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                title TEXT NOT NULL,
                amount DOUBLE PRECISION NOT NULL DEFAULT 0,
                expense_date DATE DEFAULT CURRENT_DATE,
                comment TEXT DEFAULT '',
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_clients_user ON clients(user_id);
            CREATE INDEX IF NOT EXISTS idx_jobs_user_date ON jobs(user_id,job_date);
            CREATE INDEX IF NOT EXISTS idx_expenses_user_date ON expenses(user_id,expense_date);
            CREATE INDEX IF NOT EXISTS idx_jobs_client ON jobs(client_id);
            """)
        else:
            c.executescript("""
            CREATE TABLE IF NOT EXISTS clients(
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id TEXT NOT NULL,
                name TEXT NOT NULL,
                phone TEXT DEFAULT '',
                address TEXT DEFAULT '',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE IF NOT EXISTS jobs(
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id TEXT NOT NULL,
                client_id INTEGER,
                service TEXT NOT NULL,
                price REAL NOT NULL DEFAULT 0,
                expenses REAL NOT NULL DEFAULT 0,
                address TEXT DEFAULT '',
                job_date TEXT DEFAULT CURRENT_DATE,
                comment TEXT DEFAULT '',
                status TEXT NOT NULL DEFAULT 'done',
                payment_status TEXT NOT NULL DEFAULT 'paid',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE SET NULL
            );
            CREATE TABLE IF NOT EXISTS expenses(
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id TEXT NOT NULL,
                title TEXT NOT NULL,
                amount REAL NOT NULL DEFAULT 0,
                expense_date TEXT DEFAULT CURRENT_DATE,
                comment TEXT DEFAULT '',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_clients_user ON clients(user_id);
            CREATE INDEX IF NOT EXISTS idx_jobs_user_date ON jobs(user_id,job_date);
            CREATE INDEX IF NOT EXISTS idx_expenses_user_date ON expenses(user_id,expense_date);
            CREATE INDEX IF NOT EXISTS idx_jobs_client ON jobs(client_id);
            """)


def _execute(c, sql, params=()):
    if using_postgres():
        return c.execute(sql.replace("?", "%s"), params)
    return c.execute(sql, params)


def _fetchone(c, sql, params=()):
    return _execute(c, sql, params).fetchone()


def _fetchall(c, sql, params=()):
    return _execute(c, sql, params).fetchall()


def _insert_id(c, sql, params=()):
    if using_postgres():
        return c.execute(sql + " RETURNING id", params).fetchone()["id"]
    return c.execute(sql, params).lastrowid


def _changed(c, sql, params=()):
    return _execute(c, sql, params).rowcount > 0


def validate_client(u, cid):
    if cid is None:
        return
    with get_connection() as c:
        if not _fetchone(c, "SELECT 1 FROM clients WHERE id=? AND user_id=?", (cid, u)):
            raise ValueError("Client does not belong to user")


def create_client(u, name, phone="", address=""):
    with get_connection() as c:
        return _insert_id(c, "INSERT INTO clients(user_id,name,phone,address) VALUES(?,?,?,?)", (u, name.strip(), phone.strip(), address.strip()))


def get_clients(u):
    with get_connection() as c:
        rows = _fetchall(c, """
            SELECT c.*,
                   COUNT(CASE WHEN j.status!='cancelled' THEN j.id END) AS jobs_count,
                   COALESCE(SUM(CASE WHEN j.status!='cancelled' THEN j.price ELSE 0 END),0) AS total_income
            FROM clients c
            LEFT JOIN jobs j ON j.client_id=c.id AND j.user_id=?
            WHERE c.user_id=?
            GROUP BY c.id
            ORDER BY c.id DESC
        """, (u, u))
        return [dict(r) for r in rows]


def update_client(u, i, name, phone="", address=""):
    with get_connection() as c:
        return _changed(c, "UPDATE clients SET name=?,phone=?,address=? WHERE id=? AND user_id=?", (name.strip(), phone.strip(), address.strip(), i, u))


def delete_client(u, i):
    with get_connection() as c:
        return _changed(c, "DELETE FROM clients WHERE id=? AND user_id=?", (i, u))


def create_job(u, cid, service, price, expenses, address, date, comment, status="done", payment_status="paid"):
    with get_connection() as c:
        return _insert_id(c, """
            INSERT INTO jobs(user_id,client_id,service,price,expenses,address,job_date,comment,status,payment_status)
            VALUES(?,?,?,?,?,?,?,?,?,?)
        """, (u, cid, service.strip(), price, expenses, address.strip(), date, comment.strip(), status, payment_status))


def update_job(u, i, cid, service, price, expenses, address, date, comment, status, payment_status):
    with get_connection() as c:
        return _changed(c, """
            UPDATE jobs SET client_id=?,service=?,price=?,expenses=?,address=?,job_date=?,comment=?,status=?,payment_status=?
            WHERE id=? AND user_id=?
        """, (cid, service.strip(), price, expenses, address.strip(), date, comment.strip(), status, payment_status, i, u))


def delete_job(u, i):
    with get_connection() as c:
        return _changed(c, "DELETE FROM jobs WHERE id=? AND user_id=?", (i, u))


def create_expense(u, title, amount, date, comment=""):
    with get_connection() as c:
        return _insert_id(c, "INSERT INTO expenses(user_id,title,amount,expense_date,comment) VALUES(?,?,?,?,?)", (u, title.strip(), amount, date, comment.strip()))


def update_expense(u, i, title, amount, date, comment=""):
    with get_connection() as c:
        return _changed(c, "UPDATE expenses SET title=?,amount=?,expense_date=?,comment=? WHERE id=? AND user_id=?", (title.strip(), amount, date, comment.strip(), i, u))


def delete_expense(u, i):
    with get_connection() as c:
        return _changed(c, "DELETE FROM expenses WHERE id=? AND user_id=?", (i, u))


def _period_sql(period, col):
    if using_postgres():
        if period == "week":
            return f" AND {col} >= CURRENT_DATE - INTERVAL '7 days'"
        if period == "month":
            return f" AND {col} >= CURRENT_DATE - INTERVAL '30 days'"
    else:
        if period == "week":
            return f" AND {col} >= date('now','-7 days')"
        if period == "month":
            return f" AND {col} >= date('now','-30 days')"
    return ""


def get_stats(u, period="all"):
    with get_connection() as c:
        wj = _period_sql(period, "job_date")
        we = _period_sql(period, "expense_date")
        income = _fetchone(c, f"SELECT COALESCE(SUM(price),0) AS v FROM jobs WHERE user_id=? AND status!='cancelled'{wj}", (u,))["v"] if using_postgres() else _fetchone(c, f"SELECT COALESCE(SUM(price),0) FROM jobs WHERE user_id=? AND status!='cancelled'{wj}", (u,))[0]
        job_expenses = _fetchone(c, f"SELECT COALESCE(SUM(expenses),0) AS v FROM jobs WHERE user_id=? AND status!='cancelled'{wj}", (u,))["v"] if using_postgres() else _fetchone(c, f"SELECT COALESCE(SUM(expenses),0) FROM jobs WHERE user_id=? AND status!='cancelled'{wj}", (u,))[0]
        other_expenses = _fetchone(c, f"SELECT COALESCE(SUM(amount),0) AS v FROM expenses WHERE user_id=?{we}", (u,))["v"] if using_postgres() else _fetchone(c, f"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE user_id=?{we}", (u,))[0]
        jobs = _fetchone(c, f"SELECT COUNT(*) AS v FROM jobs WHERE user_id=?{wj}", (u,))["v"] if using_postgres() else _fetchone(c, f"SELECT COUNT(*) FROM jobs WHERE user_id=?{wj}", (u,))[0]
        clients = _fetchone(c, "SELECT COUNT(*) AS v FROM clients WHERE user_id=?", (u,))["v"] if using_postgres() else _fetchone(c, "SELECT COUNT(*) FROM clients WHERE user_id=?", (u,))[0]
        unpaid = _fetchone(c, f"SELECT COALESCE(SUM(price),0) AS v FROM jobs WHERE user_id=? AND status!='cancelled' AND payment_status!='paid'{wj}", (u,))["v"] if using_postgres() else _fetchone(c, f"SELECT COALESCE(SUM(price),0) FROM jobs WHERE user_id=? AND status!='cancelled' AND payment_status!='paid'{wj}", (u,))[0]
        return {"income": float(income or 0), "expenses": float((job_expenses or 0) + (other_expenses or 0)), "profit": float((income or 0) - (job_expenses or 0) - (other_expenses or 0)), "clients": int(clients or 0), "jobs": int(jobs or 0), "unpaid": float(unpaid or 0)}


def get_summary(u):
    with get_connection() as c:
        rows = _fetchall(c, """
            SELECT substr(CAST(job_date AS TEXT),1,7) AS month,
                   COALESCE(SUM(CASE WHEN status!='cancelled' THEN price ELSE 0 END),0) AS income,
                   COALESCE(SUM(CASE WHEN status!='cancelled' THEN expenses ELSE 0 END),0) AS expenses
            FROM jobs WHERE user_id=? GROUP BY substr(CAST(job_date AS TEXT),1,7) ORDER BY month DESC LIMIT 6
        """, (u,))
        return [dict(r) for r in rows][::-1]


def get_jobs(u, limit=100):
    with get_connection() as c:
        rows = _fetchall(c, """
            SELECT jobs.*,clients.name AS client_name
            FROM jobs
            LEFT JOIN clients ON clients.id=jobs.client_id AND clients.user_id=jobs.user_id
            WHERE jobs.user_id=?
            ORDER BY jobs.job_date DESC,jobs.id DESC LIMIT ?
        """, (u, limit))
        return [dict(r) for r in rows]


def get_expenses(u, limit=100):
    with get_connection() as c:
        return [dict(r) for r in _fetchall(c, "SELECT * FROM expenses WHERE user_id=? ORDER BY expense_date DESC,id DESC LIMIT ?", (u, limit))]


def get_backup(u):
    return {"version": "9.0", "database": "postgresql" if using_postgres() else "sqlite", "clients": get_clients(u), "jobs": get_jobs(u, 5000), "expenses": get_expenses(u, 5000)}
