let cats=['Все'];let active='Все';let demo=[];
const $=s=>document.querySelector(s);
function money(v){return v==null?'Цена договорная':new Intl.NumberFormat('ru-RU').format(v)+' ₽'}
async function api(url,options={}){const r=await fetch(url,options);if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadCategories(){const data=await api('/api/marketplace/categories');cats=['Все',...data.map(x=>x.name)];renderCats()}
async function loadListings(){try{demo=await api('/api/marketplace/listings?limit=100');render()}catch(e){console.error(e);$('#listings').innerHTML='<div class="empty">Не удалось загрузить объявления</div>'}}
function renderCats(){if($('#categories'))$('#categories').innerHTML=cats.map(c=>`<button class="cat ${c===active?'active':''}" onclick="setCat(${JSON.stringify(c)})">${c}</button>`).join('');if($('#category'))$('#category').innerHTML=cats.slice(1).map(c=>`<option>${c}</option>`).join('')}
function setCat(c){active=c;render()}
function render(){renderCats();const q=($('#search')?.value||'').toLowerCase().trim();let items=demo.filter(x=>(active==='Все'||x.category===active)&&(!q||(x.title+' '+(x.description||'')+' '+(x.category||'')+' '+(x.city||'')).toLowerCase().includes(q)));const s=$('#sort').value;if(s==='cheap')items.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity));if(s==='expensive')items.sort((a,b)=>(b.price??-1)-(a.price??-1));$('#count').textContent=`${items.length} объявлений`;$('#listings').innerHTML=items.length?items.map(x=>`<article class="card"><img class="photo" src="${x.image_url||'https://placehold.co/800x500?text=MarketGo'}" alt="" loading="lazy"><div class="body"><div class="price">${money(x.price)}</div><div class="title">${escapeHtml(x.title)}</div><div class="meta">${escapeHtml(x.city||'Город не указан')} · ${escapeHtml(x.seller_name)}</div></div></article>`).join(''):'<div class="empty">Ничего не найдено</div>'}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openSell(){$('#sellModal').classList.remove('hidden')}function closeSell(){$('#sellModal').classList.add('hidden')}
async function submitListing(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('/api/marketplace/listings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('#title').value,description:$('#description').value,price:$('#price').value?Number($('#price').value):null,category:$('#category').value,seller_name:$('#seller').value,seller_contact:$('#contact').value,city:$('#city').value,image_url:$('#image').value||null})});e.target.reset();closeSell();await loadListings();alert('Объявление опубликовано!')}catch(err){alert('Ошибка публикации: '+err.message)}finally{b.disabled=false}}
loadCategories().then(loadListings).catch(()=>loadListings());