const demo=[{title:'iPhone 13 128 GB',price:35000,cat:'Электроника',city:'Москва',seller:'Алексей',image:'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80'},{title:'Велосипед городской',price:12000,cat:'Другое',city:'Москва',seller:'Иван',image:'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=800&q=80'},{title:'Ремонт стиральных машин',price:1500,cat:'Услуги',city:'Москва',seller:'Сервис Мастер',image:'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&q=80'}];
const cats=['Все','Электроника','Одежда','Дом и сад','Авто','Услуги','Другое'];let active='Все';
function money(v){return v==null?'Цена договорная':new Intl.NumberFormat('ru-RU').format(v)+' ₽'}
function renderCats(){document.querySelector('#categories').innerHTML=cats.map(c=>`<button class="cat ${c===active?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('');document.querySelector('#category').innerHTML=cats.slice(1).map(c=>`<option>${c}</option>`).join('')}
function setCat(c){active=c;render()}
function render(){renderCats();const q=document.querySelector('#search').value.toLowerCase().trim();let items=demo.filter(x=>(active==='Все'||x.cat===active)&&(!q||(x.title+' '+x.cat+' '+x.city).toLowerCase().includes(q)));const s=document.querySelector('#sort').value;if(s==='cheap')items.sort((a,b)=>a.price-b.price);if(s==='expensive')items.sort((a,b)=>b.price-a.price);document.querySelector('#count').textContent=`${items.length} объявлений`;document.querySelector('#listings').innerHTML=items.length?items.map(x=>`<article class="card"><img class="photo" src="${x.image}" alt="" loading="lazy"><div class="body"><div class="price">${money(x.price)}</div><div class="title">${x.title}</div><div class="meta">${x.city} · ${x.seller}</div></div></article>`).join(''):'<div class="empty">Ничего не найдено</div>'}
function openSell(){document.querySelector('#sellModal').classList.remove('hidden')}function closeSell(){document.querySelector('#sellModal').classList.add('hidden')}
function submitListing(e){e.preventDefault();alert('Форма готова. Следующий этап подключит POST /api/marketplace/listings к таблице marketplace_listings.');closeSell()}
render();
