const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();try{tg.setHeaderColor('#11141a');tg.setBackgroundColor('#f3f5f7')}catch(e){}}
const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(n||0))+' ₽';let currentPeriod='all', jobsCache=[], clientsCache=[], expensesCache=[];
const statusName={new:'Новая',progress:'В работе',done:'Выполнена',cancelled:'Отменена'};const payName={unpaid:'Не оплачено',partial:'Частично',paid:'Оплачено'};
async function api(url,opt={}){const initData=window.Telegram?.WebApp?.initData||'';const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData,...(opt.headers||{})}});if(!r.ok){const x=await r.json().catch(()=>({}));throw Error(x.detail||'Ошибка сервера')}return r.json()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
async function loadStats(){const s=await api('/api/stats?period='+currentPeriod);$('income').textContent=money(s.income);$('expenses').textContent=money(s.expenses);$('profit').textContent=money(s.profit);$('clientsCount').textContent=s.clients;$('jobsCount').textContent=s.jobs;$('periodLabel').textContent=currentPeriod==='all'?'За всё время':currentPeriod==='month'?'За последний месяц':'За последние 7 дней'}
async function loadClients(){clientsCache=await api('/api/clients');$('jobClient').innerHTML='<option value="">Без клиента</option>'+clientsCache.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');renderClients()}
function renderClients(){const q=($('clientsSearch')?.value||'').toLowerCase();const cs=clientsCache.filter(c=>`${c.name} ${c.phone} ${c.address}`.toLowerCase().includes(q));$('clientsList').innerHTML=cs.length?cs.map(c=>`<div class="item"><div class="item-top"><b>${esc(c.name)}</b><b>${money(c.total_income)}</b></div><div class="meta">${esc(c.phone||'Телефон не указан')}</div><div class="meta">${esc(c.address||'Адрес не указан')} · ${c.jobs_count} работ</div><div class="actions">${c.phone?`<a class="button" href="tel:${esc(c.phone)}">📞 Позвонить</a>`:''}<button onclick='editClient(${JSON.stringify(c)})'>✏️ Изменить</button><button class="danger" onclick="removeClient(${c.id})">🗑 Удалить</button></div></div>`).join(''):'<div class="empty">👥 Ничего не найдено.</div>'}
async function loadJobs(){jobsCache=await api('/api/jobs');renderJobs()}
function renderJobs(){const q=($('jobsSearch')?.value||'').toLowerCase();const js=jobsCache.filter(j=>`${j.service} ${j.client_name||''} ${j.address||''}`.toLowerCase().includes(q));$('jobsList').innerHTML=js.length?js.map(j=>`<div class="item"><div class="item-top"><b>${esc(j.service)}</b><b>${money(j.price)}</b></div><div class="badges"><span class="badge">${statusName[j.status]||j.status}</span><span class="badge">${payName[j.payment_status]||j.payment_status}</span></div><div class="meta">${esc(j.client_name||'Без клиента')} · ${esc(j.job_date)}</div>${j.address?`<div class="meta">📍 ${esc(j.address)}</div>`:''}<div class="money profit">Чистыми: ${money(j.price-j.expenses)}</div><div class="actions"><button onclick='editJob(${JSON.stringify(j)})'>✏️ Изменить</button><button class="danger" onclick="removeJob(${j.id})">🗑 Удалить</button></div></div>`).join(''):'<div class="empty">🔧 Ничего не найдено.</div>'}
async function loadExpenses(){expensesCache=await api('/api/expenses');renderExpenses()}
function renderExpenses(){const q=($('expensesSearch')?.value||'').toLowerCase();const es=expensesCache.filter(x=>`${x.title} ${x.comment||''}`.toLowerCase().includes(q));$('expensesList').innerHTML=es.length?es.map(x=>`<div class="item"><div class="item-top"><b>${esc(x.title)}</b><b>${money(x.amount)}</b></div><div class="meta">${esc(x.expense_date)}</div>${x.comment?`<div class="meta">${esc(x.comment)}</div>`:''}<div class="actions"><button onclick='editExpense(${JSON.stringify(x)})'>✏️ Изменить</button><button class="danger" onclick="removeExpense(${x.id})">🗑 Удалить</button></div></div>`).join(''):'<div class="empty">💸 Ничего не найдено.</div>'}
async function loadAll(){try{await Promise.all([loadStats(),loadClients(),loadJobs(),loadExpenses()])}catch(e){toast(e.message)}}
function setPeriod(p){currentPeriod=p;document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x.dataset.period===p));loadStats().catch(e=>toast(e.message))}
function showTab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));$(id+'Section').classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id))}
function openModal(id){$(id).classList.remove('hidden')};function closeModal(id){$(id).classList.add('hidden')}
function openClient(c=null){$('clientModalTitle').textContent=c?'Изменить клиента':'Новый клиент';$('clientId').value=c?.id||'';$('clientName').value=c?.name||'';$('clientPhone').value=c?.phone||'';$('clientAddress').value=c?.address||'';openModal('clientModal')}
function editClient(c){openClient(c)}
async function saveClient(e){e.preventDefault();try{const id=$('clientId').value;const body={name:$('clientName').value,phone:$('clientPhone').value,address:$('clientAddress').value};await api(id?'/api/clients/'+id:'/api/clients',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeModal('clientModal');await loadAll();toast(id?'Клиент изменён':'Клиент добавлен')}catch(x){toast(x.message)}}
async function removeClient(id){if(!confirm('Удалить клиента? Его работы останутся в истории.'))return;try{await api('/api/clients/'+id,{method:'DELETE'});await loadAll();toast('Клиент удалён')}catch(e){toast(e.message)}}
function openJob(j=null){$('jobModalTitle').textContent=j?'Изменить работу':'Новая работа';$('jobId').value=j?.id||'';$('jobService').value=j?.service||'';$('jobPrice').value=j?.price??'';$('jobExpenses').value=j?.expenses??0;$('jobDate').value=j?.job_date||today();$('jobStatus').value=j?.status||'done';$('jobPayment').value=j?.payment_status||'paid';$('jobAddress').value=j?.address||'';$('jobComment').value=j?.comment||'';loadClients().then(()=>{$('jobClient').value=j?.client_id||''});openModal('jobModal')}
function editJob(j){openJob(j)}
async function saveJob(e){e.preventDefault();try{const id=$('jobId').value;const body={client_id:$('jobClient').value?Number($('jobClient').value):null,service:$('jobService').value,price:Number($('jobPrice').value),expenses:Number($('jobExpenses').value||0),address:$('jobAddress').value,job_date:$('jobDate').value,comment:$('jobComment').value,status:$('jobStatus').value,payment_status:$('jobPayment').value};await api(id?'/api/jobs/'+id:'/api/jobs',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeModal('jobModal');await loadAll();toast(id?'Работа изменена':'Работа добавлена')}catch(x){toast(x.message)}}
async function removeJob(id){if(!confirm('Удалить эту работу?'))return;try{await api('/api/jobs/'+id,{method:'DELETE'});await loadAll();toast('Работа удалена')}catch(e){toast(e.message)}}
function openExpense(x=null){$('expenseModalTitle').textContent=x?'Изменить расход':'Новый расход';$('expenseId').value=x?.id||'';$('expenseTitle').value=x?.title||'';$('expenseAmount').value=x?.amount??'';$('expenseDate').value=x?.expense_date||today();$('expenseComment').value=x?.comment||'';openModal('expenseModal')}
function editExpense(x){openExpense(x)}
async function saveExpense(e){e.preventDefault();try{const id=$('expenseId').value;const body={title:$('expenseTitle').value,amount:Number($('expenseAmount').value),expense_date:$('expenseDate').value,comment:$('expenseComment').value};await api(id?'/api/expenses/'+id:'/api/expenses',{method:id?'PUT':'POST',body:JSON.stringify(body)});closeModal('expenseModal');await loadAll();toast(id?'Расход изменён':'Расход добавлен')}catch(x){toast(x.message)}}
async function removeExpense(id){if(!confirm('Удалить расход?'))return;try{await api('/api/expenses/'+id,{method:'DELETE'});await loadAll();toast('Расход удалён')}catch(e){toast(e.message)}}
async function downloadExport(){try{const initData=window.Telegram?.WebApp?.initData||'';const r=await fetch('/api/export',{headers:{'X-Telegram-Init-Data':initData}});if(!r.ok)throw Error('Не удалось выгрузить данные');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='masterbook-export.csv';a.click();URL.revokeObjectURL(a.href);toast('Экспорт готов')}catch(e){toast(e.message)}}
document.addEventListener('DOMContentLoaded',()=>{loadAll()});
window.addEventListener('online',()=>{const x=$('app-status');if(x){x.textContent='● Онлайн';x.classList.remove('offline')}});window.addEventListener('offline',()=>{const x=$('app-status');if(x){x.textContent='● Нет сети';x.classList.add('offline')}})
